version: '3'

services:
  nginx:
    image: nginx:1.16.0-alpine
    restart: always
    network_mode: 'host'
    ports:
      - "8877:8877"
    volumes:
      - '${PWD}/docker/nginx.conf:/etc/nginx/nginx.conf'
      - '${PWD}/docker/conf.d:/etc/nginx/conf.d'
      - '${PWD}/docker/www:/var/www'
      - '/etc/localtime:/etc/localtime:ro'
